server {
    listen 3000;
    server_name _;

    root /usr/share/nginx/html;

    # Allow embedding from any origin (widget use-case)
    add_header Access-Control-Allow-Origin  *;
    add_header Access-Control-Allow-Methods "GET, OPTIONS";
    add_header Cache-Control "public, max-age=60";

    location ~* \.(js|css)$ {
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
